name = "DarkClean"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Very minimal, dark personal blog theme for Hugo theme."
homepage = "http://siteforthistheme.com/"
tags = ["minimal","blog","clean","personal","dark"]
features = []
min_version = "0.24.1"

[author]
  name = "Eddy van den Aker"
  homepage = "https://eddyvandenaker.com"

